name: publish
on:
  push:
    branches: [ main ]
  workflow_dispatch: # allows running this workflow manually from the Actions tab
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'source'
          submodules: 'recursive'
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          path: 'build'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: 'source'
      - name: build
        working-directory: 'source'
        run: bundle exec jekyll build --verbose -s www -d ${{ github.workspace }}/build
        env:
          JEKYLL_ENV: production
      - name: commit_and_push
        working-directory: 'build'
        run: |
          git config user.name '${{ github.repository_owner }}'
          git config user.email '${{ github.repository_owner }}@users.noreply.github.com'
          git add -A
          git diff-index --quiet HEAD || { git commit -m 'automated github action workflow publish' && git push origin gh-pages; }
